class AppConstants{
  static const String STORAGE_DEVICE_OPEN_FIRST_TIME = "STORAGE_DEVICE_OPEN_FIRST_TIME";

  static const String STORAGE_USER_PROFILE_KEY = "STORAGE_USER_PROFILE_KEY";
  static const String STORAGE_USER_TOKEN_KEY = "STORAGE_USER_TOKEN_KEY";
}

